<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>JobAggregator.Api</AssemblyName>
	<RootNamespace>JobAggregator.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="JobAggregator.Application\**\*.cs;JobAggregator.Contracts\**\*.cs;JobAggregator.Domain\**\*.cs;JobAggregator.Infrastructure\**\*.cs;JobAggregator.Worker\**\*.cs;JobAggregator.Infrastructure.Tests\**\*.cs;**\obj\**\*.cs;**\bin\**\*.cs" />
    <Content Remove="JobAggregator.Application\**;JobAggregator.Contracts\**;JobAggregator.Domain\**;JobAggregator.Infrastructure\**;JobAggregator.Worker\**;JobAggregator.Infrastructure.Tests\**" />
    <None Remove="JobAggregator.Application\**;JobAggregator.Contracts\**;JobAggregator.Domain\**;JobAggregator.Infrastructure\**;JobAggregator.Worker\**;JobAggregator.Infrastructure.Tests\**" />
    <EmbeddedResource Remove="JobAggregator.Application\**;JobAggregator.Contracts\**;JobAggregator.Domain\**;JobAggregator.Infrastructure\**;JobAggregator.Worker\**;JobAggregator.Infrastructure.Tests\**" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.4.0" />
	<PackageReference Include="Azure.Identity" Version="1.14.2" />
	<PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
	<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.10" />
	<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
	<PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
	<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
	<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="JobAggregator.Application\JobAggregator.Application.csproj" />
	<ProjectReference Include="JobAggregator.Infrastructure\JobAggregator.Infrastructure.csproj" />
	<ProjectReference Include="JobAggregator.Contracts\JobAggregator.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="JobAggregator.Frontend\public\" />
  </ItemGroup>

</Project>
